FROM python:3.12-slim

WORKDIR /app

# Копируем файл с зависимостями
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения и тесты
COPY . .

# Копируем модули в Python path
RUN cp app/*.py .

# Запускаем тесты
CMD ["pytest", "-vv", "--tb=long", "--asyncio-mode=strict"] 