services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - ./tests/.env.test
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3 