FROM python:3.12-slim

WORKDIR /app

# Копируем только requirements.txt сначала, чтобы кэшировать слой с зависимостями
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения и тесты
COPY . .

# Запускаем тесты
CMD ["pytest", "tests/", "-v"] 