version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ASSISTANT_ID=${OPENAI_ASSISTANT_ID}
      - OPEN_API_SECRETAR_ID=test_secretary_id
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_QUEUE_TO_TELEGRAM=${REDIS_QUEUE_TO_TELEGRAM:-queue:to_telegram}
      - REDIS_QUEUE_TO_SECRETARY=${REDIS_QUEUE_TO_SECRETARY:-queue:to_secretary}
    env_file:
      - ./tests/.env.test
    volumes:
      - .:/app
      - ./tests/.env.test:/app/tests/.env.test
    depends_on:
      redis:
        condition: service_healthy 