FROM python:3.12-slim

WORKDIR /app

# Копируем только requirements.txt сначала, чтобы кэшировать слой с зависимостями
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest pytest-asyncio pytest-mock

# Копируем код приложения и тесты
COPY src/ ./src/
COPY tests/ ./tests/

# Добавляем src в PYTHONPATH
ENV PYTHONPATH=/app/src

# Запускаем тесты
CMD ["pytest", "tests/", "-v"] 