version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ASSISTANT_ID=asst_djbIGegxw5REvKxwleTmI8r7
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - ./tests/.env.test:/app/tests/.env.test
    depends_on:
      redis:
        condition: service_healthy 