services:
  test:
    build:
      context: ..
      dockerfile: telegram_bot_service/Dockerfile.test
    environment:
      - TESTING=1
      - PYTHONPATH=/src
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - REST_SERVICE_URL=http://mock:8000
      - TELEGRAM_BOT_USERNAME=test_bot
      - TELEGRAM_TOKEN=test_token
      - TELEGRAM_ID=123456789
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./tests/.env.test
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3 