"""Update UserSummary model with new fields

Revision ID: 5b008852e15c
Revises: 591852cc38c8
Create Date: 2025-05-08 15:35:11.161396+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel as sm

# revision identifiers, used by Alembic.
revision: str = '5b008852e15c'
down_revision: Union[str, None] = '591852cc38c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_summaries', sa.Column('assistant_id', sa.Uuid(), nullable=False))
    op.add_column('user_summaries', sa.Column('last_message_id_covered', sa.Integer(), nullable=True))
    op.add_column('user_summaries', sa.Column('token_count', sa.Integer(), nullable=True))
    
    op.execute("UPDATE user_summaries SET assistant_id = secretary_id")
    
    op.execute("CREATE SEQUENCE IF NOT EXISTS user_summaries_id_seq")
    op.execute("ALTER TABLE user_summaries ALTER COLUMN id TYPE INTEGER USING nextval('user_summaries_id_seq')")
    op.execute("ALTER TABLE user_summaries ALTER COLUMN id SET DEFAULT nextval('user_summaries_id_seq')")
    
    op.drop_index('ix_user_summaries_secretary_id', table_name='user_summaries')
    op.create_index(op.f('ix_user_summaries_assistant_id'), 'user_summaries', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_user_summaries_last_message_id_covered'), 'user_summaries', ['last_message_id_covered'], unique=False)
    op.drop_constraint('user_summaries_secretary_id_fkey', 'user_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'user_summaries', 'assistant', ['assistant_id'], ['id'])
    op.drop_column('user_summaries', 'secretary_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_summaries', sa.Column('secretary_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_summaries', type_='foreignkey')
    op.create_foreign_key('user_summaries_secretary_id_fkey', 'user_summaries', 'assistant', ['secretary_id'], ['id'])
    op.drop_index(op.f('ix_user_summaries_last_message_id_covered'), table_name='user_summaries')
    op.drop_index(op.f('ix_user_summaries_assistant_id'), table_name='user_summaries')
    op.create_index('ix_user_summaries_secretary_id', 'user_summaries', ['secretary_id'], unique=False)
    op.execute("ALTER TABLE user_summaries ALTER COLUMN id TYPE UUID USING gen_random_uuid()")
    op.execute("ALTER TABLE user_summaries ALTER COLUMN id DROP DEFAULT")
    op.drop_column('user_summaries', 'token_count')
    op.drop_column('user_summaries', 'last_message_id_covered')
    op.drop_column('user_summaries', 'assistant_id')
    # ### end Alembic commands ### 