"""Remove created_by_assistant_id from reminders

Revision ID: 77ec1688718c
Revises: 248f2037ffd3
Create Date: 2025-04-22 10:51:05.094907+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77ec1688718c"
down_revision: Union[str, None] = "248f2037ffd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reminder_created_by_assistant_id", table_name="reminder")
    op.drop_constraint(
        "reminder_created_by_assistant_id_fkey", "reminder", type_="foreignkey"
    )
    op.drop_column("reminder", "created_by_assistant_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reminder",
        sa.Column(
            "created_by_assistant_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "reminder_created_by_assistant_id_fkey",
        "reminder",
        "assistant",
        ["created_by_assistant_id"],
        ["id"],
    )
    op.create_index(
        "ix_reminder_created_by_assistant_id",
        "reminder",
        ["created_by_assistant_id"],
        unique=False,
    )
    # ### end Alembic commands ###
