"""add memory table

Revision ID: e9cc6eb00d30
Revises: 77a177d0696a
Create Date: 2025-12-06 11:27:25.991421+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'e9cc6eb00d30'
down_revision: Union[str, None] = '77a177d0696a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('memory_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_message_id', sa.Uuid(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_assistant_id'), 'memories', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_memories_memory_type'), 'memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_index(
        'ix_memories_embedding',
        'memories',
        ['embedding'],
        postgresql_using='hnsw',
        postgresql_with={'m': 16, 'ef_construction': 64},
        postgresql_ops={'embedding': 'vector_cosine_ops'}
    )
    op.drop_index('ix_userassistantthread_assistant_id', table_name='userassistantthread')
    op.drop_index('ix_userassistantthread_last_used', table_name='userassistantthread')
    op.drop_index('ix_userassistantthread_user_id', table_name='userassistantthread')
    op.drop_table('userassistantthread')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userassistantthread',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assistant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_used', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistant.id'], name='userassistantthread_assistant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='userassistantthread_pkey')
    )
    op.create_index('ix_userassistantthread_user_id', 'userassistantthread', ['user_id'], unique=False)
    op.create_index('ix_userassistantthread_last_used', 'userassistantthread', ['last_used'], unique=False)
    op.create_index('ix_userassistantthread_assistant_id', 'userassistantthread', ['assistant_id'], unique=False)
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_memory_type'), table_name='memories')
    op.drop_index(op.f('ix_memories_assistant_id'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ### 