"""Remove input_schema from Tool model

Revision ID: 7d3e651aa9e0
Revises: 9be5e4b9acb1
Create Date: 2025-04-21 16:10:14.005682+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7d3e651aa9e0"
down_revision: Union[str, None] = "9be5e4b9acb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool", "input_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tool",
        sa.Column("input_schema", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
