"""Add global_settings table

Revision ID: 8c7ccf2eb126
Revises: 77ec1688718c
Create Date: 2025-05-05 09:24:43.413168+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c7ccf2eb126"
down_revision: Union[str, None] = "77ec1688718c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "globalsettings",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "summarization_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("context_window_size", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("globalsettings")
    # ### end Alembic commands ###
