"""Add Message model

Revision ID: ad9c5df53922
Revises: 5b008852e15c
Create Date: 2025-05-08 15:42:23.095683+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel as sm

# revision identifiers, used by Alembic.
revision: str = 'ad9c5df53922'
down_revision: Union[str, None] = '5b008852e15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('tool_call_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistant.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['user_summaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['telegramuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_assistant_id'), 'messages', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_messages_tool_call_id'), 'messages', ['tool_call_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index('ix_messages_user_id_assistant_id_id', 'messages', ['user_id', 'assistant_id', 'id'], unique=False)
    op.create_foreign_key(None, 'user_summaries', 'messages', ['last_message_id_covered'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_summaries', type_='foreignkey')
    op.drop_index('ix_messages_user_id_assistant_id_id', table_name='messages')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_tool_call_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_assistant_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ### 