"""Add user_summaries table without unique constraint

Revision ID: 248f2037ffd3
Revises: 7d3e651aa9e0
Create Date: 2025-04-22 10:28:06.104094+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "248f2037ffd3"
down_revision: Union[str, None] = "7d3e651aa9e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_summaries",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("secretary_id", sa.Uuid(), nullable=False),
        sa.Column("summary_text", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["secretary_id"],
            ["assistant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["telegramuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_summaries_secretary_id"),
        "user_summaries",
        ["secretary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_summaries_user_id"), "user_summaries", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_summaries_user_id"), table_name="user_summaries")
    op.drop_index(op.f("ix_user_summaries_secretary_id"), table_name="user_summaries")
    op.drop_table("user_summaries")
    # ### end Alembic commands ###
