"""Add reminders table final attempt

Revision ID: d4ce9c701e57
Revises: b201a35b7385
Create Date: 2025-04-06 15:37:34.611830+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4ce9c701e57"
down_revision: Union[str, None] = "b201a35b7385"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminder",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("assistant_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_assistant_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("trigger_at", sa.DateTime(), nullable=True),
        sa.Column("cron_expression", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("last_triggered_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_assistant_id"],
            ["assistant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["telegramuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reminder_assistant_id"), "reminder", ["assistant_id"], unique=False
    )
    op.create_index(
        op.f("ix_reminder_created_by_assistant_id"),
        "reminder",
        ["created_by_assistant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reminder_trigger_at"), "reminder", ["trigger_at"], unique=False
    )
    op.create_index(op.f("ix_reminder_user_id"), "reminder", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminder_user_id"), table_name="reminder")
    op.drop_index(op.f("ix_reminder_trigger_at"), table_name="reminder")
    op.drop_index(op.f("ix_reminder_created_by_assistant_id"), table_name="reminder")
    op.drop_index(op.f("ix_reminder_assistant_id"), table_name="reminder")
    op.drop_table("reminder")
    # ### end Alembic commands ###
