"""add startup_message to assistant

Revision ID: a2b961b9ad17
Revises: 5a20a9510ebb
Create Date: 2025-05-13 21:12:37.559984+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a2b961b9ad17'
down_revision: Union[str, None] = '5a20a9510ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant', sa.Column('startup_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant', 'startup_message')
    # ### end Alembic commands ### 