"""Remove input_schema from Tool model

Revision ID: 7d3e651aa9e0
Revises: 9be5e4b9acb1
Create Date: 2025-04-21 16:10:14.005682+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d3e651aa9e0"
down_revision: Union[str, None] = "9be5e4b9acb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_checkpoints_id', table_name='checkpoints')
    # op.drop_index('ix_checkpoints_thread_id', table_name='checkpoints')
    # op.drop_table('checkpoints')
    op.drop_column("tool", "input_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tool",
        sa.Column("input_schema", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # op.create_table('checkpoints',
    # sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    # sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='checkpoints_pkey')
    # )
    # op.create_index('ix_checkpoints_thread_id', 'checkpoints', ['thread_id'], unique=False)
    # op.create_index('ix_checkpoints_id', 'checkpoints', ['id'], unique=True)
    # ### end Alembic commands ###
