"""--autogenerate

Revision ID: 591852cc38c8
Revises: 8c7ccf2eb126
Create Date: 2025-05-05 11:55:09.996854+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel as sm
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "591852cc38c8"
down_revision: Union[str, None] = "8c7ccf2eb126"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
