"""change tool_call_id to str

Revision ID: 5a20a9510ebb
Revises: ad9c5df53922
Create Date: 2025-05-11 11:13:34.516090+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a20a9510ebb"
down_revision: Union[str, None] = "ad9c5df53922"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "tool_call_id",
        existing_type=sa.UUID(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(
        "ix_user_summaries_last_message_id_covered", table_name="user_summaries"
    )
    op.drop_constraint(
        "user_summaries_last_message_id_covered_fkey",
        "user_summaries",
        type_="foreignkey",
    )
    op.drop_column("user_summaries", "last_message_id_covered")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_summaries",
        sa.Column(
            "last_message_id_covered", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "user_summaries_last_message_id_covered_fkey",
        "user_summaries",
        "messages",
        ["last_message_id_covered"],
        ["id"],
    )
    op.create_index(
        "ix_user_summaries_last_message_id_covered",
        "user_summaries",
        ["last_message_id_covered"],
        unique=False,
    )
    op.alter_column(
        "messages",
        "tool_call_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
