"""Add UserFact table

Revision ID: 9be5e4b9acb1
Revises: e62f29d63d77
Create Date: 2025-04-18 10:42:20.476425+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9be5e4b9acb1"
down_revision: Union[str, None] = "e62f29d63d77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userfact",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fact", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["telegramuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_userfact_fact"), "userfact", ["fact"], unique=False)
    op.create_index(op.f("ix_userfact_user_id"), "userfact", ["user_id"], unique=False)
    # op.drop_index("ix_checkpoints_id", table_name="checkpoints") # Removed erroneous drop
    # op.drop_index("ix_checkpoints_thread_id", table_name="checkpoints") # Removed erroneous drop
    # op.drop_table("checkpoints") # Removed erroneous drop
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table( # Removed erroneous create
    #     "checkpoints",
    #     sa.Column(
    #         "id",
    #         sa.UUID(),
    #         server_default=sa.text("gen_random_uuid()"),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.Column("thread_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    #     sa.Column(
    #         "checkpoint_blob", postgresql.BYTEA(), autoincrement=False, nullable=False
    #     ),
    #     sa.Column(
    #         "updated_at",
    #         postgresql.TIMESTAMP(timezone=True),
    #         server_default=sa.text("now()"),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "created_at",
    #         postgresql.TIMESTAMP(timezone=True),
    #         server_default=sa.text("now()"),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "checkpoint_metadata",
    #         postgresql.JSON(astext_type=sa.Text()),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.PrimaryKeyConstraint("id", name="checkpoints_pkey"),
    # )
    # op.create_index( # Removed erroneous create
    #     "ix_checkpoints_thread_id", "checkpoints", ["thread_id"], unique=False
    # )
    # op.create_index("ix_checkpoints_id", "checkpoints", ["id"], unique=True) # Removed erroneous create
    op.drop_index(op.f("ix_userfact_user_id"), table_name="userfact")
    op.drop_index(op.f("ix_userfact_fact"), table_name="userfact")
    op.drop_table("userfact")
    # ### end Alembic commands ###
