"""add metadata to checkpoint

Revision ID: 530a6ae9c8a7
Revises: 2dd537c210c1
Create Date: 2025-04-12 19:33:52.350517+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "530a6ae9c8a7"
down_revision: Union[str, None] = "2dd537c210c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checkpoints", sa.Column("checkpoint_metadata", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("checkpoints", "checkpoint_metadata")
    # ### end Alembic commands ###
