"""Placeholder for missing revision e62f29d63d77

Revision ID: e62f29d63d77
Revises: 530a6ae9c8a7
Create Date: 2024-01-01 00:00:00.000000 

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e62f29d63d77"
down_revision: Union[
    str, None
] = "530a6ae9c8a7"  # Depends on the last existing revision
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is empty because the original was lost.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is empty because the original was lost.
    pass
    # ### end Alembic commands ###
